# ==========================================
# Server Configuration (Render Compatible)
# ==========================================
server.port=${PORT:8080}
server.servlet.context-path=

# ==========================================
# Neon PostgreSQL Database Configuration
# ==========================================
spring.datasource.url=jdbc:postgresql://ep-odd-poetry-apmlh0jz-pooler.c-7.us-east-1.aws.neon.tech:5432/neondb?sslmode=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_i7ruLpWZxNI2

spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# JPA / Hibernate Configuration
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ==========================================
# JWT Security Configuration
# ==========================================
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# 1 Day in milliseconds
app.jwt.expiration=86400000
# 7 Days in milliseconds
app.jwt.refreshExpiration=604800000

# ==========================================
# Live Simulation and Logging Configuration
# ==========================================
logging.level.root=INFO
logging.level.com.devsecops.dashboard=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO

# ==========================================
# Spring Doc / Swagger OpenAPI Config
# ==========================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha

# ==========================================
# JavaMail Sender SMTP Configuration
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vallabhuanilsai2005@gmail.com
spring.mail.password=ojnizgvujauovnau
spring.mail.from=vallabhuanilsai2005@gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
